"""tournament stages

Revision ID: 06f9718d4967
Revises: fffc59fca625
Create Date: 2026-09-05 11:32:44.486000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f9718d4967'
down_revision: Union[str, None] = 'fffc59fca625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = "fk_games_stage_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'name', name='uq_tournament_stages_tournament_name')
    )
    op.create_index('idx_tournament_stages_tournament', 'tournament_stages', ['tournament_id'], unique=False)
    op.create_table('tournament_stage_advances',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_id', 'player_id')
    )
    op.add_column('games', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_index('idx_games_stage', 'games', ['stage_id'], unique=False)
    op.create_foreign_key(FK_NAME, 'games', 'tournament_stages', ['stage_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'games', type_='foreignkey')
    op.drop_index('idx_games_stage', table_name='games')
    op.drop_column('games', 'stage_id')
    op.drop_table('tournament_stage_advances')
    op.drop_index('idx_tournament_stages_tournament', table_name='tournament_stages')
    op.drop_table('tournament_stages')
    # ### end Alembic commands ###
