"""initial unified schema

Revision ID: 17ba44bdda37
Revises: 
Create Date: 2026-09-03 17:15:07.701145

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17ba44bdda37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_bot_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('favorite_role', sa.String(length=10), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('salutation', sa.String(length=20), nullable=True),
    sa.Column('affiliation', sa.String(length=20), nullable=True),
    sa.Column('can_play', sa.Boolean(), nullable=False),
    sa.Column('can_staff', sa.Boolean(), nullable=False),
    sa.Column('site_username', sa.String(length=50), nullable=True),
    sa.Column('site_password_hash', sa.Text(), nullable=True),
    sa.Column('is_site_admin', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_bot_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$'", name='ck_players_slug_format'),
    sa.CheckConstraint('site_username IS NULL OR site_password_hash IS NOT NULL', name='ck_players_site_creds'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('site_username'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_kind', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_kind IN ('site','bot')", name='ck_audit_actor_kind_enum'),
    sa.ForeignKeyConstraint(['actor_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('registration_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_players', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('results_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("game_type IN ('tournament','funky','training')", name='ck_games_type_enum'),
    sa.CheckConstraint("result IS NULL OR result IN ('city_win','mafia_win','draw')", name='ck_games_result_enum'),
    sa.CheckConstraint("status <> 'rated' OR result IS NOT NULL", name='ck_games_rated_has_result'),
    sa.CheckConstraint("status IN ('scheduled','registration_closed','played','rated')", name='ck_games_status_enum'),
    sa.ForeignKeyConstraint(['created_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_rating',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('game_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('points_win', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('points_judge', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('lh', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ci', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('info', sa.String(length=20), nullable=True),
    sa.Column('removals', sa.SmallInteger(), nullable=True),
    sa.Column('ppk', sa.Boolean(), nullable=False),
    sa.Column('zk', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('sk', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.CheckConstraint("info IS NULL OR info IN ('first_killed','killed','voted_out')", name='ck_participants_info_enum'),
    sa.CheckConstraint("role IN ('mafia','don','sheriff','citizen')", name='ck_participants_role_enum'),
    sa.CheckConstraint('lh IS NULL OR (lh >= 0 AND lh <= 1.5)', name='ck_participants_lh_range'),
    sa.CheckConstraint('removals IS NULL OR removals >= 0', name='ck_participants_removals_nonneg'),
    sa.CheckConstraint('seat_number BETWEEN 1 AND 10', name='ck_participants_seat_range'),
    sa.CheckConstraint('sk IS NULL OR sk >= 0', name='ck_participants_sk_nonneg'),
    sa.CheckConstraint('zk IS NULL OR zk >= 0', name='ck_participants_zk_nonneg'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_participants_game_player'),
    sa.UniqueConstraint('game_id', 'seat_number', name='uq_participants_game_seat')
    )
    op.create_table('player_rating_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('rating_after', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('k_coefficient', sa.SmallInteger(), nullable=False),
    sa.Column('expected_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_rating_history_player_game')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('available_from', sa.Text(), nullable=True),
    sa.Column('available_until', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('host','judge','player')", name='ck_registrations_role_enum'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_registrations_game_player')
    )
    op.create_table('reserves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_reserves_game_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserves')
    op.drop_table('registrations')
    op.drop_table('player_rating_history')
    op.drop_table('game_participants')
    op.drop_table('player_rating')
    op.drop_table('games')
    op.drop_table('audit_log')
    op.drop_table('players')
    op.drop_table('pending_bot_admins')
    # ### end Alembic commands ###
