"""add indexes

Revision ID: 182ab644c300
Revises: 17ba44bdda37
Create Date: 2026-09-03 17:16:14.372741

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182ab644c300'
down_revision: Union[str, None] = '17ba44bdda37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_participants_game', 'game_participants', ['game_id'], unique=False)
    op.create_index('idx_participants_player', 'game_participants', ['player_id'], unique=False)
    op.create_index('idx_games_starts_at', 'games', ['starts_at', 'id'], unique=False)
    op.create_index('idx_games_status', 'games', ['status'], unique=False)
    op.create_index('idx_rating_current', 'player_rating', ['rating'], unique=False)
    op.create_index('idx_players_active', 'players', ['is_active'], unique=False)
    op.create_index('idx_players_is_bot_admin', 'players', ['is_bot_admin'], unique=False, postgresql_where=sa.text('is_bot_admin'))
    op.create_index('idx_registrations_game', 'registrations', ['game_id'], unique=False)
    op.create_index('idx_registrations_player', 'registrations', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_registrations_player', table_name='registrations')
    op.drop_index('idx_registrations_game', table_name='registrations')
    op.drop_index('idx_players_is_bot_admin', table_name='players', postgresql_where=sa.text('is_bot_admin'))
    op.drop_index('idx_players_active', table_name='players')
    op.drop_index('idx_rating_current', table_name='player_rating')
    op.drop_index('idx_games_status', table_name='games')
    op.drop_index('idx_games_starts_at', table_name='games')
    op.drop_index('idx_participants_player', table_name='game_participants')
    op.drop_index('idx_participants_game', table_name='game_participants')
    # ### end Alembic commands ###
